name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with dynamic Python version 
      run: docker buildx build . --file Dockerfile --build-arg PYTHON_VERSION=3.12 --tag pokemon-classifier:3.12-$(date +%s)
