name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with dynamic Python version
      run: docker build . \
        --file Dockerfile \
        --build-arg PYTHON_VERSION=${{matrix.python-version}} \
        --tag pokemon-classifier:${{matrix.python-version}}-$(date +%s)
